export interface Player {
  // `id` is generated by the backend, so it may be absent when creating a new
  // player.  Mark it optional to make the client-side model easier to work with.
  id?: number;
  username: string;
  email: string;
}
